<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>id.co.app</groupId>
        <artifactId>wmsApi-1.0</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>wms-web</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging> <!-- Change packaging to war -->

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Dependency to wms-security module -->
        <dependency>
            <groupId>id.co.app</groupId>
            <artifactId>wms-security</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>id.co.app</groupId>
            <artifactId>wms-master</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- Other dependencies for wms-web -->
        <!-- Add your other dependencies here -->
    </dependencies>

    <build>
        <finalName>wmsApi-1.0.1</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>id.co.app.Application</mainClass>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>