spring.datasource.url=jdbc:postgresql://localhost:5432/WMS_DEV
spring.datasource.username=avrdude07
spring.datasource.password=P@ssw0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari.nodeValue=TRACE
logging.file.name=./logs/WMS-App.log
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.clean-history-on-start=true
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.file-name-pattern=./logs/WMS-App-%d{yyyy-MM-dd}.%i.log